### ISSUE TITLE
how do git?

### ISSUE THREAD

**Issue by odj2001** [KaneLindsay/MerseyTrainsLive#1]
pls help

**Comment by KaneLindsay** [comment]
- Download GitHub Desktop, it is the easiest interface
- Create a branch of our project by cloning the main branch (this repository)
- Make your edits to the code inside the project file on your PC
- Push your edits to your branch
- When you have finished a new feature, use the Desktop app to ask for a pull request to the main branch
- I will merge your branch to the main branch
